import type { TaskRecord } from '../../shared/types/domain'

type TaskText = { tasks: string; taskRunning: string; recentTasks: string; cancel: string; retry: string; viewLog: string; close: string; refresh: string }

export function TaskPanel({ tasks, log, text, onClose, onCancel, onRetry, onLog }: { tasks: TaskRecord[]; log: { id: string; content: string } | null; text: TaskText; onClose: () => void; onCancel: (id: string) => Promise<void>; onRetry: (id: string) => Promise<void>; onLog: (id: string) => Promise<void> }) {
  const active = tasks.filter((task) => task.status === 'queued' || task.status === 'running' || task.status === 'waiting_input')
  const recent = tasks.filter((task) => !active.includes(task)).slice(0, 12)
  const renderTask = (task: TaskRecord) => <article className="task-row" key={task.id}><div className="task-copy"><strong>{task.kind.replaceAll('-', ' ')}</strong><span>{task.stage} · {task.resourceKeys.join(', ')}</span>{task.error !== null && <span className="task-error">{task.error}</span>}<div className="task-progress"><i style={{ width: `${task.progress}%` }} /></div></div><div className="task-actions"><span className={`task-status ${task.status}`}>{task.status}</span>{(task.status === 'queued' || task.status === 'running') && <button type="button" className="secondary" onClick={() => { void onCancel(task.id) }}>{text.cancel}</button>}{['failed', 'cancelled', 'interrupted'].includes(task.status) && <button type="button" className="secondary" onClick={() => { void onRetry(task.id) }}>{text.retry}</button>}<button type="button" className="secondary" onClick={() => { void onLog(task.id) }}>{text.viewLog}</button></div></article>
  return <aside className="task-panel" aria-label={text.tasks}><div className="task-panel-header"><div><p className="eyebrow">{text.tasks}</p><h2>{active.length} {text.taskRunning}</h2></div><button type="button" className="secondary" onClick={onClose}>{text.close}</button></div>{active.length > 0 && <section className="task-group">{active.map(renderTask)}</section>}<p className="task-group-title">{text.recentTasks}</p><section className="task-group">{recent.map(renderTask)}{recent.length === 0 && <p className="field-help">No task history.</p>}</section>{log !== null && <section className="task-log"><div><strong>{text.viewLog}</strong><button type="button" className="secondary" onClick={() => { void onLog(log.id) }}>{text.refresh}</button></div><pre>{log.content || 'No log output yet.'}</pre></section>}</aside>
}
