//! Bundling glue for the `@deepseek-ai/dsh-box-context` Cordis plugin.
//!
//! The npm package lives beside this crate as `dsh-box-context/`; this
//! library only exposes constants and a small renderer the Rust
//! container-start path uses to keep names and JSON shape in lockstep.

/// Cordis plugin id used by every entry and patch overlay.
pub const PLUGIN_ID: &str = "dsh-box-context";

/// Scoped npm package name; must match `dsh-box-context/package.json#name`
/// verbatim because DSH resolves it through Node's standard `require`
/// machinery.
pub const PLUGIN_PACKAGE: &str = "@deepseek-ai/dsh-box-context";

/// Default prompt-context order. Sandbox policy owns 110, approval policy
/// 115, subagent delegation 120; 130 leaves room for one more authoritative
/// section without colliding with the 100–199 tool-guidance band.
pub const DEFAULT_ORDER: u32 = 130;

/// Relative path under `<container>/state/` for the JSON snapshot Box writes
/// on every container start.
pub const SNAPSHOT_FILENAME: &str = "dsh-box-context.json";

/// Relative path under `<container>/state/` for the Cordis patch overlay
/// that mounts the plugin with `contextFile` pointing at the snapshot.
pub const PATCH_FILENAME: &str = "dsh-box-context.patch.yml";

/// Pair of paths under `<container>/state/`: the JSON snapshot the plugin
/// reads, and the Cordis patch overlay DSH's loader consumes.
#[derive(Debug, Clone)]
pub struct DshContextFiles {
    /// Absolute path to the JSON snapshot file.
    pub snapshot_path: std::path::PathBuf,
    /// Absolute path to the Cordis patch yml file.
    pub patch_path: std::path::PathBuf,
}

/// Render the JSON snapshot Box writes for one container start.
///
/// The plugin renders this verbatim as a `dsh-box:container` system-prompt
/// context (order 130) once the JSON is read at apply time, so every
/// field here becomes an authoritative fact the agent sees in its
/// user-role history snapshot.
///
/// `api_key_envs` is the list of `<env_name> = <key>` pairs read from
/// `<DSH_HOME>/.credentials.yaml`; we only ship the env name (the key
/// value stays out of the prompt path), so the agent can reference the
/// provider without the secret ever leaving its source file.
#[allow(clippy::too_many_arguments)]
pub fn render_snapshot(
    container_id: &str,
    container_name: &str,
    version: &str,
    profile: &str,
    workspace: &std::path::Path,
    profile_home: &std::path::Path,
    plugins_root: &std::path::Path,
    skills_root: &std::path::Path,
    logs_root: &std::path::Path,
    api_key_envs: &[String],
) -> String {
    let snapshot = serde_json::json!({
        "container": {
            "id": container_id,
            "name": container_name,
            "version": version,
            "profile": profile,
        },
        "paths": {
            "workspace": workspace.display().to_string(),
            "profileHome": profile_home.display().to_string(),
            "plugins": plugins_root.display().to_string(),
            "skills": skills_root.display().to_string(),
            "logs": logs_root.display().to_string(),
        },
        "credentials": {
            "providers": api_key_envs.iter().map(|env| {
                serde_json::json!({ "apiKeyEnv": env })
            }).collect::<Vec<_>>(),
        },
    });
    serde_json::to_string_pretty(&snapshot).unwrap_or_else(|_| "{}".to_owned())
}

/// Render the Cordis patch yml that mounts the plugin with `contextFile`
/// pointing at the JSON snapshot.
pub fn render_patch_yml(snapshot_path: &std::path::Path, order: u32) -> String {
    // Cordis patches emit JSON-compatible YAML; we keep the order explicit
    // so the entry lands in the global prompt layer with the configured
    // order even if defaults change upstream.
    //
    // NOTE: assemble each line with `concat!` instead of `\` line
    // continuation. A trailing `\` strips ALL leading whitespace of the
    // next source line, which flattens the nested list indentation into
    // invalid YAML and makes DSH fail at startup with "end of the stream
    // or a document separator is expected".
    format!(
        concat!(
            "# Generated by dshbox on every Container start. Mounts the\n",
            "# `@deepseek-ai/dsh-box-context` plugin so the agent's user-role\n",
            "# history snapshot carries this Container's structured metadata.\n",
            "- insert:\n",
            "  - id: {plugin_id}\n",
            "    name: '{plugin_package}'\n",
            "    config:\n",
            "      contextFile: {snapshot_path}\n",
            "      order: {order}\n",
        ),
        plugin_id = PLUGIN_ID,
        plugin_package = PLUGIN_PACKAGE,
        snapshot_path = snapshot_path.display(),
        order = order,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn snapshot_includes_container_metadata_and_paths() {
        let json = render_snapshot(
            "container-1",
            "my box",
            "latest",
            "web",
            &PathBuf::from("/run/ws"),
            &PathBuf::from("/run/profile"),
            &PathBuf::from("/run/plugins"),
            &PathBuf::from("/run/skills"),
            &PathBuf::from("/run/logs"),
            &["MINIMAX_CN_API_KEY".to_owned()],
        );
        let v: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert_eq!(v["container"]["id"], "container-1");
        assert_eq!(v["container"]["name"], "my box");
        assert_eq!(v["paths"]["workspace"], "/run/ws");
        assert_eq!(v["credentials"]["providers"][0]["apiKeyEnv"], "MINIMAX_CN_API_KEY");
    }

    #[test]
    fn patch_yml_inserts_plugin_with_config() {
        let yml = render_patch_yml(&PathBuf::from("/run/state/dsh-box-context.json"), DEFAULT_ORDER);
        // `- insert:` must be followed by a properly indented nested list;
        // flattened indentation (a `\` continuation bug) yields unparsable
        // YAML and DSH refuses to boot.
        assert!(yml.contains("- insert:\n  - id: dsh-box-context"));
        assert!(yml.contains("  - id: dsh-box-context\n    name: '@deepseek-ai/dsh-box-context'"));
        assert!(yml.contains("    config:\n      contextFile: /run/state/dsh-box-context.json"));
        assert!(yml.contains(format!("      order: {}\n", DEFAULT_ORDER).as_str()));
        assert!(!yml.lines().any(|line| line.starts_with("name:") && !line.starts_with("    name:")));
    }
}
