import { useMemo, useState } from 'react'
import type { ContainerExtensions, DshContainer } from '../../shared/types/domain'

type Text = { pluginRepo: string; pluginRepoNote: string; noRepositoryPlugins: string; exportPlugin: string; installTo: string; profile: string; install: string; exporting: string }
type Props = { containers: DshContainer[]; details: Record<string, ContainerExtensions>; text: Text; onInstall: (id: string, profile: string, source: string) => Promise<void>; onExport: (sourceContainerId: string, sourcePath: string, name: string) => Promise<void> }

export function PluginRepo({ containers, details, text, onInstall, onExport }: Props) {
  const entries = useMemo(() => Object.entries(details).flatMap(([containerId, item]) => item.profiles.flatMap((profile) => profile.plugins.filter((plugin) => plugin.path && !plugin.name.startsWith('@deepseek-ai/')).map((plugin) => ({ ...plugin, containerId, profile: profile.name, sourceName: containers.find((container) => container.id === containerId)?.name ?? containerId })))), [containers, details])
  const [target, setTarget] = useState(containers[0]?.id ?? '')
  const [profile, setProfile] = useState(containers[0]?.profile ?? 'web')
  return <section className="workspace"><p className="eyebrow">PLUGINS</p><h1>{text.pluginRepo}</h1><p className="workspace-note">{text.pluginRepoNote}</p><div className="extension-list plugin-repo-list">{entries.length ? entries.map((plugin) => <article key={`${plugin.containerId}-${plugin.profile}-${plugin.name}`} className="extension-row"><div><strong>{plugin.name}</strong><p>{plugin.description ?? plugin.diagnostic ?? ''}</p><p>{plugin.sourceName} · {plugin.profile}</p></div><div className="plugin-repo-actions"><code>{plugin.version ?? '—'}</code><button type="button" className="secondary" onClick={() => { void onExport(plugin.containerId, plugin.path!, plugin.name) }}>{text.exportPlugin}</button><label>{text.installTo}<select value={target} onChange={(event) => { const id = event.target.value; setTarget(id); setProfile(containers.find((container) => container.id === id)?.profile ?? 'web') }}>{containers.map((container) => <option key={container.id} value={container.id}>{container.name}</option>)}</select></label><label>{text.profile}<input value={profile} onChange={(event) => { setProfile(event.target.value) }} /></label><button type="button" className="primary" disabled={!target || !profile.trim()} onClick={() => { void onInstall(target, profile.trim(), plugin.path!) }}>{text.install}</button></div></article>) : <p className="empty-extension">{text.noRepositoryPlugins}</p>}</div></section>
}
