[package]
name = "box-state"
version = "0.1.0"
edition = "2021"

[dependencies]
box-foundation = { path = "../box-foundation" }
box-scheduler = { path = "../box-scheduler" }
box-toolchains = { path = "../box-toolchains" }
box-dsh-versions = { path = "../box-dsh-versions" }
box-containers = { path = "../box-containers" }
box-extensions = { path = "../box-extensions" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
