import { useEffect, useState } from 'react'
import type { ContainerExtensions, DshContainer } from '../../shared/types/domain'

export type ContainerDetailsText = {
  back: string; activeProfile: string; profiles: string; addProfile: string; profilePlaceholder: string; plugins: string; skills: string; noPlugins: string; noSkills: string; containerSkill: string; diagnostics: string; version: string; addExtension: string; extensionSource: string; browseArchive: string; adding: string
}
type Tab = 'profiles' | 'plugins' | 'skills'
type Props = { container: DshContainer; details: ContainerExtensions | null; text: ContainerDetailsText; onBack: () => void; onAddProfile: (profile: string) => Promise<void>; onSelectProfile: (profile: string) => Promise<void>; onAddExtension: (profile: string, source: string) => Promise<void>; onChooseArchive: () => Promise<string | null> }

export function ContainerDetails({ container, details, text, onBack, onAddProfile, onSelectProfile, onAddExtension, onChooseArchive }: Props) {
  const [profile, setProfile] = useState(container.profile); const [newProfile, setNewProfile] = useState(''); const [source, setSource] = useState(''); const [saving, setSaving] = useState(false); const [tab, setTab] = useState<Tab>('profiles')
  useEffect(() => { setProfile(container.profile) }, [container.id, container.profile])
  const selected = details?.profiles.find((item) => item.name === profile) ?? details?.profiles[0]
  async function selectProfile(value: string, persist: boolean): Promise<void> { if (!persist) { setProfile(value); return }; setSaving(true); try { await onSelectProfile(value); setProfile(value) } finally { setSaving(false) } }
  async function addProfile(): Promise<void> { const value = newProfile.trim(); if (!value) return; setSaving(true); try { await onAddProfile(value); setProfile(value); setNewProfile('') } finally { setSaving(false) } }
  async function addExtension(): Promise<void> { const value = source.trim(); if (!value || !selected) return; setSaving(true); try { await onAddExtension(selected.name, value); setSource('') } finally { setSaving(false) } }
  async function browse(): Promise<void> { const path = await onChooseArchive(); if (path) setSource(path) }
  return <section className="workspace container-detail-view"><button type="button" className="back-button" onClick={onBack}>← {text.back}</button><p className="eyebrow">CONTAINER</p><h1>{container.name}</h1><section className="container-detail-summary"><span>{container.id}</span><span>{text.version}: {container.version}</span></section>
    <nav className="extension-tabs" aria-label="Container detail sections">{(['profiles', 'plugins', 'skills'] as Tab[]).map((item) => <button type="button" key={item} className={tab === item ? 'active' : ''} onClick={() => { setTab(item) }}>{text[item]}</button>)}</nav>
    {tab === 'profiles' && <section className="extensions-section"><div className="extensions-heading"><h2>{text.profiles}</h2><label>{text.activeProfile}<select value={container.profile} disabled={saving || !selected} onChange={(event) => { void selectProfile(event.target.value, true) }}>{details?.profiles.map((item) => <option key={item.name} value={item.name}>{item.name}</option>)}</select></label></div><div className="profile-create"><input value={newProfile} placeholder={text.profilePlaceholder} onChange={(event) => { setNewProfile(event.target.value) }} /><button type="button" className="secondary" disabled={saving || !newProfile.trim()} onClick={() => { void addProfile() }}>{text.addProfile}</button></div></section>}
    {(tab === 'plugins' || tab === 'skills') && <section className="extensions-section"><div className="extensions-heading"><h2>{text[tab]}</h2>{tab === 'plugins' && <label>{text.profiles}<select value={selected?.name ?? ''} disabled={saving || !selected} onChange={(event) => { void selectProfile(event.target.value, false) }}>{details?.profiles.map((item) => <option key={item.name} value={item.name}>{item.name}</option>)}</select></label>}</div><div className="extension-import"><input value={source} placeholder={text.extensionSource} onChange={(event) => { setSource(event.target.value) }} /><button type="button" className="secondary" disabled={saving} onClick={() => { void browse() }}>{text.browseArchive}</button><button type="button" className="primary" disabled={saving || !source.trim() || !selected} onClick={() => { void addExtension() }}>{saving ? text.adding : text.addExtension}</button></div>{tab === 'plugins' ? <div className="extension-list">{selected?.plugins.length ? selected.plugins.map((plugin) => <article key={plugin.name} className="extension-row"><div><strong>{plugin.name}</strong><p>{plugin.description ?? plugin.diagnostic ?? ''}</p></div><div><code>{plugin.version ?? '—'}</code>{plugin.path && <p className="path">{plugin.path}</p>}</div></article>) : <p className="empty-extension">{text.noPlugins}</p>}</div> : <div className="extension-list">{details?.skills.length ? details.skills.map((skill) => <article key={skill.path} className="extension-row"><div><strong>{skill.name}</strong><p>{skill.description ?? skill.diagnostic ?? ''}</p></div><div><span className="extension-source">{text.containerSkill}</span><p className="path">{skill.path}</p></div></article>) : <p className="empty-extension">{text.noSkills}</p>}</div>}</section>}
    {details?.diagnostics.length ? <section className="extension-diagnostics"><strong>{text.diagnostics}</strong>{details.diagnostics.map((item) => <p key={item}>{item}</p>)}</section> : null}
  </section>
}
