[package]
name = "box-store"
version = "0.1.0"
edition = "2021"

[dependencies]
box-foundation = { path = "../box-foundation" }
box-scheduler = { path = "../box-scheduler" }
rusqlite = { version = "0.32", features = ["bundled"] }
serde_json = "1.0"
tracing.workspace = true

[dev-dependencies]
box-foundation = { path = "../box-foundation", features = ["test-kit"] }
